import type { Metadata } from "next";
import Container from "@/components/Container";
import CTABlock from "@/components/CTABlock";

export const metadata: Metadata = {
  title: "About Dativo",
  description:
    "Dativo builds compliance infrastructure for the EU Data Act. Purpose-built for industrial manufacturers of connected products.",
  alternates: {
    canonical: "https://dativo.dev/about",
  },
};

export default function AboutPage() {
  return (
    <>
      {/* Hero */}
      <section className="py-24 sm:py-32">
        <Container>
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-sm font-semibold uppercase tracking-wider text-grey-accent">
              About
            </p>
            <h1 className="mt-4 font-heading text-4xl font-bold tracking-tight text-navy sm:text-5xl text-balance">
              Building compliance infrastructure for connected products
            </h1>
            <p className="mt-6 text-lg leading-relaxed text-grey-accent">
              Dativo exists to make EU Data Act compliance operationally
              feasible for every connected product manufacturer — from a
              50-person OEM running Docker Compose to a €5B industrial group
              deploying on Kubernetes.
            </p>
          </div>
        </Container>
      </section>

      {/* Mission */}
      <section className="bg-navy/[0.02] py-20 sm:py-24">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h2 className="font-heading text-3xl font-bold tracking-tight text-navy">
              Our Mission
            </h2>
            <div className="mt-6 space-y-4 text-base leading-relaxed text-grey-accent">
              <p>
                The EU Data Act (Regulation (EU) 2023/2854) represents a
                fundamental shift in how manufacturers must handle the data
                generated by their connected products. Since September 2025,
                customers have a legal right to access the data produced by
                the products they purchase, and to share it with third parties
                of their choice.
              </p>
              <p>
                This creates a complex operational challenge: manufacturers must
                build infrastructure to register equipment, map data sources,
                classify trade secrets, and fulfill data access requests —
                continuously, for every customer, every product line, and every
                new data source. Doing this manually doesn&apos;t scale.
              </p>
              <p>
                Dativo exists to solve this problem. We provide the open-core
                platform that makes EU Data Act compliance operational,
                auditable, and scalable — so manufacturers can focus on
                building great products.
              </p>
            </div>
          </div>
        </Container>
      </section>

      {/* Values */}
      <section id="careers" className="py-20 sm:py-24">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h2 className="font-heading text-3xl font-bold tracking-tight text-navy">
              Our Principles
            </h2>
            <div className="mt-8 grid gap-8 sm:grid-cols-2">
              {[
                {
                  title: "Built by engineers who use AI to move fast",
                  description:
                    "We ship in weeks what others plan for quarters. Our team embraces AI as a development accelerator — not just a product feature, but a way we build. The result is faster iteration and higher quality.",
                },
                {
                  title: "Open Source Commitment",
                  description:
                    "We believe the compliance engine should be transparent and auditable. The Community Edition is genuinely useful — not a lead gen trap. The commercial features exist because enterprise compliance, advanced integrations, and managed infrastructure are genuinely harder problems worth paying for.",
                },
                {
                  title: "Regulatory Depth",
                  description:
                    "We don't build generic data tools. Every feature is designed around specific Data Act articles and their practical implications for manufacturers.",
                },
                {
                  title: "Industrial Focus",
                  description:
                    "We understand manufacturing environments — the data volumes, the integration complexity, the deployment constraints. CISOs at industrial OEMs won't send equipment telemetry to third-party clouds. That's why we offer self-hosted deployment with source transparency.",
                },
              ].map((value) => (
                <div key={value.title}>
                  <h3 className="font-heading text-lg font-semibold text-navy">
                    {value.title}
                  </h3>
                  <p className="mt-2 text-sm leading-relaxed text-grey-accent">
                    {value.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </Container>
      </section>

      <CTABlock
        title="Join us in building the future of industrial data compliance"
        description="We're always looking for talented people who are passionate about regulatory technology and industrial infrastructure."
        buttonText="Get in Touch"
        buttonHref="/contact"
      />
    </>
  );
}
