export function OrganizationJsonLd() {
  const data = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Dativo',
    url: 'https://dativo.dev',
    logo: 'https://dativo.dev/logos/logo-dark-on-white.svg',
    description:
      'EU Data Act compliance platform for connected product manufacturers.',
    sameAs: [
      'https://github.com/unio-lab/dativo',
      'https://www.linkedin.com/company/dativo-eu',
    ],
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  )
}

export function SoftwareApplicationJsonLd() {
  const data = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Dativo',
    url: 'https://dativo.dev',
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Web',
    description:
      'Operational platform enabling connected product manufacturers to comply with the EU Data Act (Regulation (EU) 2023/2854).',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'EUR',
      description: 'Community Edition — free and open source',
    },
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  )
}

export function FAQPageJsonLd() {
  const data = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is the EU Data Act?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'The EU Data Act (Regulation (EU) 2023/2854) is a regulation requiring manufacturers of connected products to share product-generated data with customers and authorized third parties. It has been enforceable since September 12, 2025.',
        },
      },
      {
        '@type': 'Question',
        name: 'What are the penalties for EU Data Act non-compliance?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Member states set their own penalty frameworks, but the regulation allows for fines of up to 4% of global annual turnover — the same ceiling as GDPR.',
        },
      },
      {
        '@type': 'Question',
        name: 'Which manufacturers are affected by the EU Data Act?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Any manufacturer of connected products sold in the EU that generate data through sensors, software, or network connectivity. This includes industrial machinery, HVAC systems, pumps, valves, construction equipment, energy systems, and consumer IoT devices.',
        },
      },
      {
        '@type': 'Question',
        name: 'What data must manufacturers share under the EU Data Act?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Under Article 3, manufacturers must make product data and related service data readily accessible to users. Under Article 4, users can request any data generated by their connected product. Under Articles 5–6, users can designate third parties to receive their data.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is Article 4(3) trade secret protection?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Manufacturers can withhold specific data if disclosure would cause serious economic damage through trade secret exposure. However, they must provide structured justification under Directive (EU) 2016/943 and offer a confidentiality agreement as an alternative.',
        },
      },
      {
        '@type': 'Question',
        name: 'How long do manufacturers have to respond to data access requests?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'The Data Act requires data to be made available "without undue delay" and within the same quality as the data holder receives. There is no fixed number of days, but the expectation from guidance documents is prompt fulfillment, typically interpreted as within 30 days.',
        },
      },
    ],
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  )
}
